
package com.cold.translationservice.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.11
 * 2015-02-02T15:53:17.470+08:00
 * Generated source version: 2.7.11
 */

@WebFault(name = "Exception", targetNamespace = "http://server.translationService.cold.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.cold.translationservice.client.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.cold.translationservice.client.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.cold.translationservice.client.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.cold.translationservice.client.Exception getFaultInfo() {
        return this.exception;
    }
}
